[sse]
user = www-data
group = www-data

listen = 0.0.0.0:9001
pm = static
pm.max_children = 50

request_terminate_timeout = 3600s

access.log = /proc/self/fd/2
access.format = "[%t] %m %{REQUEST_URI}e (DOCUMENT_URI: %{DOCUMENT_URI}e) -> %s"
